<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
if (!empty($finalPriceModel->getAmount()->getBaseAmount())
    && ($priceModel->getAmount()->getBaseAmount()) != 0
    && ($priceModel->getAmount()->getBaseAmount()) > ($finalPriceModel->getAmount()->getBaseAmount())) {
    $youSave = ($priceModel->getAmount()->getBaseAmount()) - ($finalPriceModel->getAmount()->getBaseAmount());
    $percent = round(($youSave/($priceModel->getAmount()->getBaseAmount()))*100);
}
?>
<?php if ($block->hasSpecialPrice()) :?>
    <p class="old-price">
        <span class="retail-price">Retail Price:</span>
        <?= $block->renderAmount($priceModel->getAmount(), [
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </p>
    <p class="special-price">
        <span class="your-price">Your Price:</span>
        <?= $block->renderAmount($finalPriceModel->getAmount(), [
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true
        ]); ?>
    </p>
    <p class="save-price">
        <span class="save-label">You Save:</span>
        <span class="price">
            <?= "$" . $youSave . " (" . $percent . "%)" ?>
        </span>
    </p>
<?php else :?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
