<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2020 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($postList = trim($this->getPostListHtml())): ?>
    <?php echo $postList ?>
<?php else: ?>
    <p class="note-msg"><?php echo __('There are no posts matching your selection.') ?></p>
<?php endif; ?>
