<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_SubscribenowPro
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var \Magedelight\Subscribenow\Block\Catalog\Product\View\Subscription $block */
?>
<?php if ($block->canDisplaySubscription()): ?>
    <fieldset class="fieldset admin__fieldset">
        <legend class="legend admin__legend">
            <span><?= __('Subscription Options')?></span>
        </legend>
        
        <input type="hidden" name="productviewpage" value="yes" />

        <?php echo $block->getChildHtml('subscription.type'); ?>
        <?php echo $block->getChildHtml('billing.period'); ?>
        <?php echo $block->getChildHtml('billing.date'); ?>
        <?php echo $block->getChildHtml('additional.info'); ?>
        
    </fieldset>
<?php endif; ?>