<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2020 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <div class="contact-content row">
        <div class="contact-form clearfix">
			<div class="fix-width col-xs-12 col-sm-12 col-md-12">
				<fieldset class="fieldset">
					<div class="field name required">
						<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
						<div class="control">
							<input  name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
						</div>
					</div>
					<div class="field email required">
						<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
						<div class="control">
							<input  name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="field telephone">
						<label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
						<div class="control">
							<input  name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" value="" class="input-text" type="text" />
						</div>
					</div>
					<div class="field comment required">
						<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></label>
						<div class="control">
							<textarea  name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Comment') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
						</div>
					</div>
					<?php echo $block->getChildHtml('form.additional.info'); ?>
					<div class="actions-toolbar">
						<div class="primary">
							<input type="hidden" name="hideit" id="hideit" value="" />
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
								<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
							</button>
                            <p class="required"><em>* </em><?php /* @escapeNotVerified */ echo __('Required Fields') ?></p>
						</div>
					</div>
				</fieldset>
			</div>
    	</div>
    </div>
</form>
