<div class="software-landing cms-landing">
    <div class="landing-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-7 col-lg-7">
                    <div class="text">
                        <h1 data-wow-delay="0.2s" class="wow fadeInDown">Take control of your payroll with our powerful software </h1>
                        <p>Keeping track of employees hours is one of the most important parts of your business. You want to make sure you are billed for the right time, but you don't want to be cheated either. The process should be simple, fast and efficient, and that is exactly what we had in mind when we developed our Time & Attendance software.</p>
                        <p>Combined with our state of the art fingerprint or facial time clocks, our Made-in- USA software can reduce your monthly payroll costs by 10% to 20% which, in turn, adds profit to your bottom line every month! This truly is a product that will pay for itself. Explore all of the features, screenshots and options that our software has to offer.</p>
                        <p><small><i>Our software is compatible with Windows XP, Windows 7, Windows 8 & 8.1, Windows 10 and Windows Server. Not MAC compatible.</i></small></p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-5 col-lg-5">
                    <img class="wow fadeInRight" src="<?php echo $block->getViewFileUrl('images/dummy/top-promo-image.png') ?>">
                </div>
            </div>
        </div>
    </div>
    <div class="features-section block-section">
        <div class="container">
            <div class="title-box">
                <h3 data-wow-delay="0.2s" class="wow fadeInDown">Features</h3>
                <div class="sub-title">
                    <p>We created our Time & Attendance Software with clients in mind: an easy to use interface that is simple to navigate. We loaded it with great features so that you can manage your employees time from A to Z, all in one place, with minimal effort. Here are some of the main cool features we offer: </p>
                </div>
            </div>
            <div class="content-box">
                <ul data-wow-delay="0.2s" class="list-features wow fadeInUp">
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Records Modifications</strong>
                            <p>Add a missed punch, edit an existing record or delete a duplicate punch, all with one simple click of your mouse.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Round Off Times</strong>
                            <p>Choose a pre-defined rule, or create your own rule and automatically round off your employee’s hours.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Job Codes</strong>
                            <p>Commonly used for job costing, or if different jobs pay different amounts, this feature allows you to keep track of time worked per employee on individual tasks, in addition to total hours worked cumulatively.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Employees Schedules</strong>
                            <p>Create and manage employee schedules, so that you can keep track of late or absent personnel. Save your most commonly used shifts and assign them to employees with one simple click.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Manage Time Off</strong>
                            <p>Track employee Vacation, Sick, Personal and Holiday hours so that you know exactly how many were used and remain for the current year. You can also accrue vacation and sick hours, based on actual hours worked.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Track Overtime/Doubletime</strong>
                            <p>This feature allows you to enter your own parameters to track overtime and doubletime byemployee or department on a per day, per week or bi-weekly basis.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Work Status Dashboard</strong>
                            <p>One centralized screen that instantly displays who’s in, late, or absent, so that you can monitor your entire work force quickly and efficiently.</p>
                        </div>
                    </li>
                    <li>
                        <div class="item-inner">
                            <div class="icon-box">
                                <img src="<?php echo $block->getViewFileUrl('images/dummy/feature-icon1.png') ?>">
                            </div>
                            <strong>Lunch & Breaks Policies</strong>
                            <p>This feature allows you enter your own parameters for break and lunch periods, whether they be paid or unpaid, so that all calculations are handled appropriately, according to your specific requirements.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="report-section block-section">
        <div class="div-wrapper">
            <div class="title-box">
                <h3 data-wow-delay="0.2s" class="wow fadeInDown">Report Center</h3>
                <div class="sub-title">
                    <p>With over 10 reports available, our powerful Report Center will provide any information you need regarding your employees times: whether you're looking for a basic summary of the total hours worked, a complete report detailing every single punch, a report showing absences/tardies or a spreadsheet showing the total hours worked per job, we have it all.</p>
                </div>
            </div>
            <div class="content-box clearfix">
                <div class="content-desktop">
                    <div class="list-tabs">
                        <ul>
                            <li data-tab="tab-1" class="active">HOURS REPORT</li>
                            <li data-tab="tab-2">SUMMARY REPORT</li>
                            <li data-tab="tab-3">JOB CODES REPORT</li>
                            <li data-tab="tab-4">TIME OFF REPORT</li>
                            <li data-tab="tab-5">DAILY ATTENDANCE STATISTICS</li>
                            <li data-tab="tab-6">ABSENCE REPORT </li>
                        </ul>
                    </div>
                    <div id="report-accordion" class="clearfix">
                        <div class="tab-title" id="tab-1">
                            <span>HOURS REPORT</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy.png') ?>">
                        </div>
                        <div class="tab-title" id="tab-2">
                            <span>SUMMARY REPORT</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy-2.png') ?>">
                        </div>
                        <div class="tab-title" id="tab-3">
                            <span>JOB CODES REPORT</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy3.png') ?>">
                        </div>
                        <div class="tab-title" id="tab-4">
                            <span>TIME OFF REPORT</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy.png') ?>">
                        </div>
                        <div class="tab-title" id="tab-5">
                            <span>DAILY ATTENDANCE STATISTICS</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy-2.png') ?>">
                        </div>
                        <div class="tab-title" id="tab-6">
                            <span>ABSENCE REPORT</span>
                        </div>
                        <div class="tab-content">
                            <img src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy3.png') ?>">
                        </div>
                    </div>
                </div>
                <div class="content-mobile">
                    <div class="list-tabs">
                        <ul>
                            <li>HOURS REPORT</li>
                            <li>SUMMARY REPORT</li>
                            <li>JOB CODES REPORT</li>
                            <li>TIME OFF REPORT</li>
                            <li>DAILY ATTENDANCE STATISTICS</li>
                            <li>ABSENCE REPORT </li>
                        </ul>
                    </div>
                    <div class="list-slider">
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy.png') ?>">
                        </div>
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy-2.png') ?>">
                        </div>
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy3.png') ?>">
                        </div>
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy.png') ?>">
                        </div>
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy-2.png') ?>">
                        </div>
                        <div class="slide-item">
                            <img data-skip-lazy="1" src="<?php echo $block->getViewFileUrl('images/dummy/report-img-dummy3.png') ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="package-section block-section">
        <div class="container">
            <div class="title-box">
                <h3 data-wow-delay="0.2s" class="wow fadeInDown">Standard vs Professional Edition</h3>
                <div class="sub-title">
                    <p>Whether you choose Standard or Professional edition, you will have access to all the great features described under the Feature section above. Upgrading to the Professional edition of our Software will enable the additional features below to enhance your experience and facilitate your work.</p>
                </div>
            </div>
            <div class="content-box">
                <div class="package-head">
                    <div class="left" data-toggle="text-left"><span class="text-inner">Standard Edition</span></div>
                    <div class="right active" data-toggle="text-right"><span class="text-inner">Professional Edition</span></div>
                </div>
                <ul class="list-option">
                    <li>
                        <div class="text-left"><span class="text-inner w-279">Up to 50 Employees</span></div>
                        Number of Employees you can manage
                        <div class="text-right active"><span class="text-inner w-279">Unlimited</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">1</span></div>
                        Number of Companies you can manage
                        <div class="text-right active"><span class="text-inner w-178">Unlimited</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner w-178">1 PC at a time</span></div>
                        Number of Software Installation
                        <div class="text-right active"><span class="text-inner  w-279">Up to 5 PCs at the same time</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">1</span></div>
                        Number of Software Administrators
                        <div class="text-right active"><span class="text-inner w-178">Unlimited</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Password Protect access to the software
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Multiple level of permissions: User permissions can be defined to allow or restrict access to Employee Control, Device Management, Reports, Exports and/or specific Departments. Furthermore, there is a footprint, so that you can easily identify if a record was modified and by whom.
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner  w-279">Up to 5 time clocks</span></div>
                        Number of Time Clocks you can manage
                        <div class="text-right active"><span class="text-inner  w-279">Up to 20 time clocks</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Remote access time clock through LAN, WAN, VPN or Internet (For Internet access, a static public IP address and router with port forwarding is required.)
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">Access</span></div>
                        Type of database
                        <div class="text-right active"><span class="text-inner w-178">Access or SQL</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Archiving your database Archive punches from previous year to speed up your reports. You can access the archived data at any time (Access database only)
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Database Maintenance: Repair and compact your database to keep your software operating smoothly (Access database only)
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Automatic backup of the software database (Access database only)
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Export your employee’s hours and payment information to QuickBooks, ADP, PAYCHEX, CSV, Heartland, GMS, CheckMark, TotalTrack, CPI or Replicon.
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                    <li>
                        <div class="text-left"><span class="text-inner">No</span></div>
                        Schedule an automatic download of punches from your time clock to the software
                        <div class="text-right active"><span class="text-inner">Yes</span></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="screenshot-section block-section">
        <div class="div-wrapper">
            <div class="title-box">
                <h3 data-wow-delay="0.2s" class="wow fadeInDown">Screenshots</h3>
            </div>
            <div class="content-box">
                <div class="slider center">
                    <div class="slide-item">
                        <a href="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>">
                            <img data-skip-lazy="1" src="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>" alt="slide image"/>
                        </a>
                    </div>
                    <div class="slide-item">
                        <a href="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>">
                            <img data-skip-lazy="1" src="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>" alt="slide image"/>
                        </a>
                    </div>
                    <div class="slide-item">
                        <a href="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>">
                            <img data-skip-lazy="1" src="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>" alt="slide image"/>
                        </a>
                    </div>
                    <div class="slide-item">
                        <a href="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>">
                            <img data-skip-lazy="1" src="<?= $block->getViewFileUrl('images/dummy/slide-dummy.png') ?>" alt="slide image"/>
                        </a>
                    </div>
                </div>
                <p class="text-note"> (Click an image to view at full size)</p>
            </div>
        </div>
    </div>
    <div class="choose-us block-section">
        <div class="div-wrapper">
            <div class="title-box">
                <h3 data-wow-delay="0.2s" class="wow fadeInDown">Why Choose Us?</h3>
            </div>
            <div class="content-box">
                <ul data-wow-delay="0.2s" class="wow fadeInUp">
                    <li class="fee">
                        <div class="item-inner">
                            <strong class="label">NO MONTHLY FEES!</strong>
                            <p>There are NO on-going monthly fees or yearly subscriptions with our time clocks or software. No licenses to renew, no mandatory enrollment, etc.</p>
                        </div>
                    </li>
                    <li class="check">
                        <div class="item-inner">
                            <strong class="label">FEATURE PACKED SOFTWARE</strong>
                            <p>Take advantage of the many features our software has to offer. The best part is: Any software updates are always available to all clients for free!</p>
                        </div>
                    </li>
                    <li class="support">
                        <div class="item-inner">
                            <strong class="label">OUTSTANDING SUPPORT</strong>
                            <p>You can rely on our expert product support team, trained to answer any questions you may have on the time clocks or software. (Extended technical support requires the purchase of an optional support plan).</p>
                        </div>
                    </li>
                    <li class="like">
                        <div class="item-inner">
                            <strong class="label">TOP OF THE LINE FINGERPRINT SENSORS</strong>
                            <p>We've been developing and improving our fingerprint sensors for the last 10 years. They are among the fastest and most efficient in the industry.</p>
                        </div>
                    </li>
                    <li class="save-money">
                        <div class="item-inner">
                            <strong class="label">COMPETITIVE PRICES</strong>
                            <p>We offer our clients the best product/software/support, always at the lowest prices possible.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

