<?php
/**
 * *
 * * @author    Tigren Solutions <info@tigren.com>
 * * @copyright Copyright (c) 2020 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * * @license   Open Software License ("OSL") v. 1.0.0
 *
 */
?>
<form class="form form-orders-search"
      id="oar-widget-orders-and-returns-form"
      data-mage-init='{"ordersReturns":{}, "validation":{}}'
      action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
      method="post" name="customer_post">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>"/>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Order Information')) ?></span></legend>
        <div class="field id">
            <label class="label" for="oar-order-id"><span><?= $block->escapeHtml(__('Order Number')) ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"/>
            </div>
        </div>
        <div id="oar-phonenumber" class="field phonenumber">
            <label class="label" for="oar_phonenumber"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text"  class="input-text" id="oar_phonenumber" name="oar_phonenumber"
                       data-validate="{'validate-phonenumber':true}"/>
            </div>
        </div>
        <div id="oar-ordercomments" class="field ordercomments">
            <label class="label" for="oar_ordercomment"><span><?= $block->escapeHtml(__('Order Comments')) ?></span></label>
            <div class="control">
                <input type="text"  class="input-text" id="oar_ordercomments" name="oar_ordercomments"
                       data-validate="{'validate-ordercomment':true}"/>
            </div>
        </div>
        <div id="oar-email" class="field email">
            <label class="label" for="oar_email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
            <div class="control">
                <input type="email"  class="input-text" id="oar_email" name="oar_email"
                       data-validate="{'validate-email':true}"/>
            </div>
        </div>
        <div id="oar-zip" class="field zip">
            <label class="label" for="oar_zip"><span><?= $block->escapeHtml(__('ZIP Code')) ?></span></label>
            <div class="control">
                <input type="text"  class="input-text" id="oar_zip" name="oar_zip"/>
            </div>
        </div>
        <div class="field lastname">
            <label class="label" for="oar-billing-lastname"><span><?= $block->escapeHtml(__('Customer Last Name')) ?></span></label>
            <div class="control">
                <input type="text"  class="input-text" id="oar-billing-lastname" name="oar_billing_lastname"/>
            </div>
        </div>
        <div class="field company">
            <label class="label" for="oar-company"><span><?= $block->escapeHtml(__('Company Name')) ?></span></label>
            <div class="control">
                <input type="text"  class="input-text" id="oar-company" name="oar_company"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>
    </div>
</form>
