<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $helper \Tigren\ProductThumbnail\Helper\Data
 * @var $reviewHelper \Tigren\Review\Helper\Data
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$helper = $this->helper('Tigren\ProductThumbnail\Helper\Data');
$mediaUrl = $helper->getMediaUrl();
$reviewHelper = $this->helper('Tigren\Review\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showAddto = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        echo $_aloHelper->getGridStyle('.product-items .product-item'); // Config Product Grid
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $showAddto = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-products clearfix products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-list">' : '</li><li class="item product product-list">' ?>
                <!-- mode view list -->
                <?php if ($block->getMode() == 'list'): ?>
                    <div class="product-item-info category-products-list" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image?>
                        <div class="images-container">
                            <div class="product-hover">
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                            </div>
                            <?php $thumbnailIds = $helper->getThumbnailIds($_product->getId()); ?>
                            <?php if (!empty($thumbnailIds)): ?>
                                <span class="product-thumbnails-container">
                                <?php foreach ($thumbnailIds as $thumId): ?>
                                    <?php $thums = $helper->getThumbnail($thumId);
                                    if (!empty($thums) && $thums->getData('status') == 1):
                                        $thumbnailUrl = $mediaUrl . $thums->getData('image'); ?>
                                        <span class="product-thumbnails-wrapper">
                                            <img class="product-thumbnail" src="<?= $thumbnailUrl ?>"/>
                                        </span>
                                    <?php
                                    endif;
                                endforeach; ?>
                                    </span>
                            <?php endif; ?>
                        </div>

                        <div class="product details product-item-details clearfix">
                            <div class="products-textlink clearfix">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h2 class="product name product-name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */
                                       echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h2>

                                <?php // Review?>
                                <?php if ($reviewHelper->isReviewEnabled() && $reviewHelper->getRatingSummary($_product)->getReviewsCount()) : ?>
                                <?php $rating = $reviewHelper->getRatingSummary($_product)->getRatingSummary(); ?>
                                <div class="ratings" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                                    <?php if ($rating) :?>
                                        <div class="rating-box">
                                            <div class="rating" style="width:<?= $block->escapeHtmlAttr($rating); ?>%"></div>
                                        </div>
                                        <p class="rating-links">
                                            <span><?= ($reviewHelper->getRatingSummary($_product)->getReviewsCount() . " " . $block->escapeHtml(__('Review(s)'))) ?></span>
                                        </p>
                                    <?php endif;?>
                                </div>
                                <?php endif;?>

                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif; ?>

                                <?php echo $block->getProductDetailsHtml($_product); ?>
                            </div>
                            <?php if ($showAddto): ?><?php /* @showAddto */ ?>
                                <div class="product-item-inner">
                                    <div
                                        class="product actions-no product-item-actions clearfix"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <?php /* @escapeNotVerified */
                                        echo $block->getProductPrice($_product) ?>
                                        <div
                                            class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                                    echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary button btn-cart">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                            echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                            echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                            echo $_productNameStripped ?>" class="action more">
                                                <button type="button" class="button btn"><?php /* @escapeNotVerified */
                                                    echo __('Learn More') ?></button>
                                            </a>
                                        </div>
                                        <div data-role="add-to-links"
                                             class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist link-wishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <i class="fa fa-plus icons"></i>
                                                    <?php /* @escapeNotVerified */
                                                    echo __('Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <i class="fa fa-plus icons"></i>
                                                <?php echo __('Compare') ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; /* End showAddto */ ?>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- and / mode view list -->
                <!-- mode view grid -->
                <?php if ($block->getMode() == 'grid'): ?>
                    <div class="product-item-info per-product category-products-grid" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image?>
                        <div class="images-container">
                            <div class="product-hover">
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                            </div>
                            <?php $thumbnailIds = $helper->getThumbnailIds($_product->getId()); ?>
                            <?php if (!empty($thumbnailIds)): ?>
                                <?php foreach ($thumbnailIds as $thumId): ?>
                                    <?php $thums = $helper->getThumbnail($thumId);
                                    if (!empty($thums) && $thums->getData('status') == 1):
                                        $thumbnailUrl = $mediaUrl . $thums->getData('image'); ?>
                                        <span class="product-thumbnails-container">
                                    <span class="product-thumbnails-wrapper">
                                        <img class="product-thumbnail" src="<?= $thumbnailUrl ?>" max-width="50px"
                                             max-height="50px"/>
                                    </span>
                                </span>
                                    <?php
                                    endif;
                                endforeach; ?>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                            <div class="products-textlink clearfix">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h2 class="product name product-name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */
                                       echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h2>

                                <?php // Review?>
                                <?php if ($reviewHelper->isReviewEnabled() && $reviewHelper->getRatingSummary($_product)->getReviewsCount()) : ?>
                                    <?php $rating = $reviewHelper->getRatingSummary($_product)->getRatingSummary(); ?>
                                    <div class="ratings" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                                        <?php if ($rating) :?>
                                            <div class="rating-box">
                                                <div class="rating" style="width:<?= $block->escapeHtmlAttr($rating); ?>%"></div>
                                            </div>
                                            <p class="rating-links">
                                                <span><?= ($reviewHelper->getRatingSummary($_product)->getReviewsCount() == 1) ? $reviewHelper->getRatingSummary($_product)->getReviewsCount() . " " . $block->escapeHtml(__('Review')) : $reviewHelper->getRatingSummary($_product)->getReviewsCount() . " " . $block->escapeHtml(__('Review(s)')) ?></span>
                                            </p>
                                        <?php endif;?>
                                    </div>
                                <?php endif;?>

                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif; ?>

                            </div>
                            <div class="actions-no hover-box">
                                <div class="product-item-inner actions clearfix">
                                    <div
                                        class="product product-item-actions show-box"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <?php /* @escapeNotVerified */
                                        echo $block->getProductPrice($_product) ?>
                                        <div
                                            class="actions-primary actions-cart"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                                    echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary button btn-cart pull-left-none">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
                                                            echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                            echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                            echo $_productNameStripped ?>"
                                               class="action more"><?php /* @escapeNotVerified */
                                                echo __('Learn More') ?></a>
                                        </div>
                                        <div data-role="add-to-links"
                                             class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist link-wishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <i class="fa fa-heartbeat icons"></i>
                                                    <?php /* @escapeNotVerified */
                                                    echo __('Add Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <i class="fa fa-refresh icons"></i>
                                                <?php echo __('Add Compare') ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- and / mode view grid -->
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom ">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
