<?php
namespace Magecomp\Googlelangtranslator\Model;

class Language
{
    protected $_options;

    public function toOptionArray()
    {
        if (!$this->_options)
        {
            $this->_options = array(
                array('label' => 'Afrikaans', 'value' => 'af'),
                array('label' => 'Albanian', 'value' => 'sq'),
                array('label' => 'Arabic', 'value' => 'ar'),
                array('label' => 'Amharic', 'value' => 'am'),
                array('label' => 'Armenian', 'value' => 'hy'),
                array('label' => 'Azerbaijani', 'value' => 'az'),
                array('label' => 'Basque', 'value' => 'eu'),
                array('label' => 'Belarusian', 'value' => 'be'),
                array('label' => 'Bengali', 'value' => 'bn'),
                array('label' => 'Bosnian', 'value' => 'bs'),
                array('label' => 'Bulgarian', 'value' => 'bg'),
                array('label' => 'Catalan', 'value' => 'ca'),
                array('label' => 'Cebuano', 'value' => 'ceb'),
                array('label' => 'Chichewa', 'value' => 'ny'),
                array('label' => 'Chinese (Simplified)', 'value' => 'zh-CN'),
                array('label' => 'Chinese (Traditional)', 'value' => 'zh-TW'),
                array('label' => 'Croatian', 'value' => 'hr'),
                array('label' => 'Czech', 'value' => 'cs'),
                array('label' => 'Danish', 'value' => 'da'),
                array('label' => 'Dutch', 'value' => 'nl'),
                array('label' => 'English', 'value' => 'en'),
                array('label' => 'Esperanto', 'value' => 'eo'),
                array('label' => 'Estonian', 'value' => 'et'),
                array('label' => 'Filipino', 'value' => 'tl'),
                array('label' => 'Faroese', 'value' => 'fo'),
                array('label' => 'Finnish', 'value' => 'fi'),
                array('label' => 'French', 'value' => 'fr'),
                array('label' => 'Galician', 'value' => 'gl'),
                array('label' => 'Georgian', 'value' => 'ka'),
                array('label' => 'German', 'value' => 'de'),
                array('label' => 'Greek', 'value' => 'el'),
                array('label' => 'Gujarati', 'value' => 'gu'),
                array('label' => 'Haitian', 'value' => 'ht'),
                array('label' => 'Hausa', 'value' => 'ha'),
                array('label' => 'Hebrew', 'value' => 'iw'),
                array('label' => 'Hindi', 'value' => 'hi'),
                array('label' => 'Hmong', 'value' => 'hmn'),
                array('label' => 'Hungarian', 'value' => 'hu'),
                array('label' => 'Icelandic', 'value' => 'is'),
                array('label' => 'Igbo', 'value' => 'ig'),
                array('label' => 'Indonesian', 'value' => 'id'),
                array('label' => 'Irish', 'value' => 'ga'),
                array('label' => 'Italian', 'value' => 'it'),
                array('label' => 'Japanese', 'value' => 'ja'),
                array('label' => 'Javanese', 'value' => 'jv'),
                array('label' => 'Kannada', 'value' => 'kn'),
                array('label' => 'Khmer', 'value' => 'km'),
                array('label' => 'Korean', 'value' => 'ko'),
                array('label' => 'Kazakh', 'value' => 'kk'),
                array('label' => 'Lao', 'value' => 'lo'),
                array('label' => 'Latin', 'value' => 'la'),
                array('label' => 'Latvian', 'value' => 'lv'),
                array('label' => 'Lithuanian', 'value' => 'lt'),
                array('label' => 'Macedonian', 'value' => 'mk'),
                array('label' => 'Malay', 'value' => 'ms'),
                array('label' => 'Malagasy', 'value' => 'mg'),
                array('label' => 'Maltese', 'value' => 'mt'),
                array('label' => 'Maori', 'value' => 'mi'),
                array('label' => 'Marathi', 'value' => 'mr'),
                array('label' => 'Malayalam', 'value' => 'ml'),
                array('label' => 'Mongolian', 'value' => 'mn'),
                array('label' => 'Norwegian', 'value' => 'no'),
                array('label' => 'Nepali', 'value' => 'ne'),
                array('label' => 'Persian', 'value' => 'fa'),
                array('label' => 'Polish', 'value' => 'pl'),
                array('label' => 'Portuguese', 'value' => 'pt'),
                array('label' => 'Punjabi', 'value' => 'pa'),
                array('label' => 'Romanian', 'value' => 'ro'),
                array('label' => 'Russian', 'value' => 'ru'),
                array('label' => 'Serbian', 'value' => 'sr'),
                array('label' => 'Slovak', 'value' => 'sk'),
                array('label' => 'Slovenian', 'value' => 'sl'),
                array('label' => 'Sesotho', 'value' => 'st'),
                array('label' => 'Somali', 'value' => 'so'),
                array('label' => 'Sinhalese', 'value' => 'si'),
                array('label' => 'Spanish', 'value' => 'es'),
                array('label' => 'Swahili', 'value' => 'sw'),
                array('label' => 'Sundanese', 'value' => 'su'),
                array('label' => 'Swedish', 'value' => 'sv'),
                array('label' => 'Tajik', 'value' => 'tg'),
                array('label' => 'Tamil', 'value' => 'ta'),
                array('label' => 'Telugu', 'value' => 'te'),
                array('label' => 'Thai', 'value' => 'th'),
                array('label' => 'Turkish', 'value' => 'tr'),
                array('label' => 'Ukrainian', 'value' => 'uk'),
                array('label' => 'Urdu', 'value' => 'ur'),
                array('label' => 'Uzbek', 'value' => 'uz'),
                array('label' => 'Vietnamese', 'value' => 'vi'),
                array('label' => 'Welsh', 'value' => 'cy'),
                array('label' => 'Xhosa', 'value' => 'xh'),
                array('label' => 'Yiddish', 'value' => 'yi'),
                array('label' => 'Yoruba', 'value' => 'yo'),
                array('label' => 'Zulu', 'value' => 'zu'),
            );
        }
        return $this->_options;
    }
}