<?php
/**
 * Magiccart
 * @category 	Magiccart
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/)
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2018-03-15 00:23:32
 * @@Function:
 */
?>
<?php

$accordion = $this->_sysCfg->accordion;
if(!$accordion['enabled']) return;
// drawMainMenu vs DrowMobileMenu
$hideCatId = '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Framework\App\Request\Http $request */
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$frontName      = $request->getFrontName();
$isBlog = $frontName == 'blog' ? true : false;
$menuHtml = $this->drawMainMenu(true);
$mobileMenu = $menuHtml['mobile'];
if(isset($accordion['notIncludeNav'])){
    $hideCatId = $accordion['notIncludeNav'];
    $ids  = explode(',', $accordion['notIncludeNav']);
}
?>
<div class="accordion-container">
    <div class="meanmenu-accordion">
        <h3 class="accor-title"><?php echo __($this->getRootName())?></h3>
        <ul class="accordion nav-accordion" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $mobileMenu ?>
        </ul>
        <div class="all-cat"><span><?php /* @escapeNotVerified */ echo __('All Categories')?></span><span style="display:none"><?php /* @escapeNotVerified */ echo __('Close')?></span></div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery','magiccart/easing','magicmenu']);
</script>
