<?php
/**
 * Magedelight
 * Copyright (C) 2018 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2018 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php if ($block->hasAdditionalInfo()): ?>
<table id="plan-attribute-specs-table" class="data table table-order-items recent">
    <tbody>
    <?php foreach ($this->getAdditionalInfo() as $label => $value):?>
        <tr class="first odd">
            <th class="label"><?php echo $label; ?>:</th>
            <td class="data last"><?php echo $value; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;

