<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Subscribenow
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>

<?php if ($block->isCustomerDefined()): ?>
<div id="product-subscription-customer" class="product-options-wrapper">
    <div class="fieldset">
        <div class="field required">
            <label for="billing_period" class="label"><span><?php echo __('Subscription') ?></span></label>
            <div class="control">
                <select title="<?php echo __('Subscription') ?>" class=" required  admin__control-select" id="billing_period" name="billing_period">
                    <?php foreach ($block->getBillingPeriods() as $period => $periodLabel): ?>
                        <option value="<?php echo $period ?>" <?= $block->isSelected($period); ?>><?php echo $periodLabel ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
</div>
<?php else: ?>
    <div class="product-options-wrapper" id="product-subscription-admin">
        <div>
            <label class="label"><?php echo $block->getAdminDefinedBillingLabel(); ?></label>
        </div>
    </div>
<?php endif; ?>
