<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
* @var $helper \Tigren\CategoryVideo\Helper\Data
*/
?>
<?php
$helper = $this->helper('Tigren\CategoryVideo\Helper\Data');
$url = $helper->getVideoUrl();
?>
<div id="popup-modal-banner-video" style="display:none;">
    <div class="video-popup">
        <div class="video-wrapper">
            <iframe width="600" height="500" src="<?= $url ?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Tigren_CategoryVideo/js/banner-video": {}
        }
    }

</script>
